### ISSUE TITLE
Getting error " python: can't open file 'video_blend.py': [Errno 2] No such file or directory"

### ISSUE THREAD

**Issue by vishal-chudasama-sony** [gustavorayo/video-to-cartoon#2]
I gopt below error
" python: can't open file 'video_blend.py': [Errno 2] No such file or directory"

When calling the function called 'advanced_propagation' from style_propagator.py file.

I checked the repo, video_blend.py is not there.
Can you please help with this error?

**Comment by gustavorayo** [comment]
Dear [vishal-chudasama-sony](https://github.com/vishal-chudasama-sony)
The file video_blend.py is in a subproject. Did you clone the project using the recursive option?
git clone **--recursive** git@github.com:gustavorayo/video-to-cartoon.git
regards,
