### ISSUE TITLE
Perhaps there is a serious issue in video-to-cartoon/tmp/frames  folder

### ISSUE THREAD

**Issue by KeesariVigneshwarReddy** [gustavorayo/video-to-cartoon#3]
I used this Video by Luciann Photography from Pexels: https://www.pexels.com/video/wood-sea-landscape-nature-3971351/
to generate a cartoonized background video.

<img width="647" alt="image" src="https://github.com/user-attachments/assets/4d1e16ee-a6a9-40ed-81ab-9c539419710f">

I am running the code in Kaggle notebook.

This is the snippet I am using.
```
!python "vid2cartoon.py" --input_video "/kaggle/input/videos/3971351-uhd_3840_2160_25fps.mp4" --style Van-Gogh --frames 10 --output two.mp4
```

My assumption - The program is requesting for the frame files which are not yet created.

# Take a look at my kaggle output window and tmp directory.

### kaggle output window

<img width="222" alt="image" src="https://github.com/user-attachments/assets/4ad7ed1f-e49e-4caf-9ad6-e24f23666ae2">

### tmp directory
<img width="232" alt="image" src="https://github.com/user-attachments/assets/6b4b3f1c-06b6-422c-97e9-eb52ea274c6b">

**Comment by gustavorayo** [comment]
Dear KeesariVigneshwarReddy,

Thank you for reporting the issue. I have added a fix.
You might also need to install these dependencies to work in Kaggle:

`!pip install imageio==2.9.0`
`!pip install imageio-ffmpeg==0.4.2`

regards,
